; Little Buddy — M5Stick S3, NUS BLE, display-only
; 擦除: pio run -t erase
; 烧录: pio run -t upload

[platformio]
default_envs = m5stack-sticks3

[env:m5stack-sticks3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.arduino.memory_type = qio_opi
build_flags =
    -DBOARD_M5STICK_S3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM
lib_deps =
    m5stack/M5Unified
    m5stack/M5GFX
    bblanchon/ArduinoJson@^7.0.0
